language: node_js

node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'

services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop
  - docker pull clkao/postgres-plv8:9.5
  - docker run -d -p 5432:5432 clkao/postgres-plv8:9.5

script:
  - npm test
  - npm run nsp
